server:
  port: 8080

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/account
    username: root
    password: aneelap
    driver-class-name: com.mysql.cj.jdbc.Driver
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

message: hello local account
